server:
  port: 8077

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://master:3306/spark_project?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456

mybatis:
  # mapper配置文件路径
  mapper-locations: classpath:mapper/*.xml
  # 配置实体类包路径
  type-aliases-package: com.dqsy.sparkvisualization.entity